// Keep the language picker in the business-priority order used across the site.
export const locales = ["ru", "uk", "de", "en"] as const;
export type Locale = (typeof locales)[number];

export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);

const dictionaries = {
  en: {
    nav: { home: "Home", catalog: "Catalogue", story: "About", trade: "Register", search: "Search", samples: "Basket" },
    hero: { eyebrow: "CURTAIN TRIMMINGS · DECORATIVE DETAILS", title: "This detail changes everything.", body: "Tassels, wall hooks, rosettes, fringes, piping, braids and cords that complete a curtain scheme and bring the whole interior together.", primary: "Explore the catalogue", secondary: "Choose samples" },
    home: { categories: "Curtain trimmings", latest: "New details for interiors", latestBody: "New designs, textures and colour combinations for curtains, soft furnishings and upholstery.", process: "From concept to finished scheme", processBody: "We help you select curtain trimmings by style, colour, size and project needs.", step1: "Choose a design", step1Body: "Find the right tassel, fringe, braid, cord, wall hook or rosette by article and category.", step2: "Compare colours", step2Body: "Open the colourways, study the texture and add suitable samples to your basket.", step3: "Confirm your order", step3Body: "We confirm availability, dimensions, composition, price and lead time.", viewAll: "Open the full catalogue", tradeTitle: "The finishing touch for a complete interior.", tradeBody: "We source trimmings for private interiors, design projects, curtain studios and repeat supply.", talk: "Discuss a project" },
    catalog: { eyebrow: "CURTAIN TRIMMINGS CATALOGUE", title: "Details for beautifully finished curtains.", body: "Tassels, wall hooks, rosettes, fringes, piping, braids and cords in a considered range of styles and colours. Browse by article, category and texture.", search: "Search by article or name", all: "All", results: "articles", sort: "Sort", newest: "Newest", sku: "Article A–Z", loadMore: "Show more articles" },
    product: { new: "New", colours: "colourways", add: "Add to basket", added: "Added", original: "Original collection name", priceFrom: "from", priceOnRequest: "Price on request", tradePrice: "Trade price — sign in", availability: "Availability", inStock: "In stock", lowStock: "Low stock", preorder: "Pre-order", availabilityOnRequest: "Confirm availability", meter: "m", each: "pc" },
    samples: { name: "Your name", email: "Email", phone: "Phone", company: "Company", country: "Country", city: "City", address: "Delivery address", postcode: "Postcode", notes: "Project notes", checkout: "Order details", subtotal: "Verified-price subtotal", includesOnRequest: "Plus items priced on request", quoteNote: "The subtotal uses verified Nora TrimTex trade prices. Availability, delivery and unpriced items are confirmed before payment.", send: "Place order request", sending: "Placing order…", success: "Order received", successBody: "We saved your order. Our team will confirm pricing, availability and delivery.", continue: "Continue shopping", empty: "Your basket is empty.", error: "Could not place the order. Please try again." },
    footer: { note: "Curtain trimmings and decorative textile details for interiors.", legal: "© 2026 Nora TrimTex. All rights reserved." },
    categories: { "tassels-large": "Large tassels", "tassels-small": "Small tassels", "tassel-trim": "Tassel fringes", "decorative-tapes": "Borders & braids", fringe: "Fringes", "cord-fringe": "Cord fringes", cords: "Cords & piping", holdbacks: "Wall hook / rosette", home: "Home", samples: "Sample" }
  },
  de: {
    nav: { home: "Start", catalog: "Katalog", story: "Über uns", trade: "Registrierung", search: "Suchen", samples: "Warenkorb" },
    hero: { eyebrow: "VORHANGZUBEHÖR · DEKORATIVE DETAILS", title: "Dieses Detail verändert alles.", body: "Quasten, Wandhaken, Rosetten, Fransen, Paspeln, Borten und Kordeln, die Vorhänge vollenden und den Raum gestalterisch zusammenführen.", primary: "Katalog entdecken", secondary: "Muster auswählen" },
    home: { categories: "Zubehör für Vorhänge", latest: "Neue Details für Interieurs", latestBody: "Neue Modelle, Texturen und Farbkombinationen für Vorhänge, Heimtextilien und Polster.", process: "Von der Idee zum fertigen Raum", processBody: "Wir helfen bei der Auswahl nach Stil, Farbe, Größe und Projektanforderung.", step1: "Design auswählen", step1Body: "Finden Sie Quasten, Fransen, Borten, Kordeln, Wandhaken oder Rosetten nach Artikel und Kategorie.", step2: "Farben vergleichen", step2Body: "Öffnen Sie die Farbvarianten, prüfen Sie die Textur und legen Sie Muster in den Warenkorb.", step3: "Bestellung abstimmen", step3Body: "Wir bestätigen Verfügbarkeit, Maße, Material, Preis und Lieferzeit.", viewAll: "Gesamten Katalog öffnen", tradeTitle: "Das Detail, das den Raum vollendet.", tradeBody: "Wir liefern Zubehör für private Interieurs, Designprojekte, Gardinenstudios und regelmäßigen Bedarf.", talk: "Projekt besprechen" },
    catalog: { eyebrow: "KATALOG FÜR VORHANGZUBEHÖR", title: "Details für perfekt vollendete Vorhänge.", body: "Quasten, Wandhaken, Rosetten, Fransen, Paspeln, Borten und Kordeln in ausgewählten Stilen und Farben. Filtern Sie nach Artikel, Kategorie und Textur.", search: "Artikel oder Name suchen", all: "Alle", results: "Artikel", sort: "Sortierung", newest: "Neueste", sku: "Artikel A–Z", loadMore: "Weitere Artikel anzeigen" },
    product: { new: "Neu", colours: "Farbvarianten", add: "In den Warenkorb", added: "Hinzugefügt", original: "Originalname der Kollektion", priceFrom: "ab", priceOnRequest: "Preis auf Anfrage", tradePrice: "Trade-Preis — anmelden", availability: "Verfügbarkeit", inStock: "Auf Lager", lowStock: "Wenig Bestand", preorder: "Vorbestellung", availabilityOnRequest: "Verfügbarkeit anfragen", meter: "m", each: "Stk." },
    samples: { name: "Ihr Name", email: "E-Mail", phone: "Telefon", company: "Unternehmen", country: "Land", city: "Ort", address: "Lieferadresse", postcode: "Postleitzahl", notes: "Projekthinweise", checkout: "Bestelldaten", subtotal: "Zwischensumme mit bestätigten Preisen", includesOnRequest: "Zuzüglich Artikel auf Anfrage", quoteNote: "Die Zwischensumme nutzt geprüfte Trade-Preise von Nora TrimTex. Verfügbarkeit, Lieferung und offene Preise werden vor Zahlung bestätigt.", send: "Bestellung anfragen", sending: "Wird gesendet…", success: "Bestellung eingegangen", successBody: "Ihre Bestellung wurde gespeichert. Wir bestätigen Preise, Verfügbarkeit und Lieferung.", continue: "Weiter einkaufen", empty: "Ihr Warenkorb ist leer.", error: "Bestellung fehlgeschlagen. Bitte erneut versuchen." },
    footer: { note: "Vorhangzubehör und dekorative Textildetails für Interieurs.", legal: "© 2026 Nora TrimTex. Alle Rechte vorbehalten." },
    categories: { "tassels-large": "Große Quasten", "tassels-small": "Kleine Quasten", "tassel-trim": "Quastenfransen", "decorative-tapes": "Bordüren & Borten", fringe: "Fransen", "cord-fringe": "Kordelfransen", cords: "Kordeln & Paspeln", holdbacks: "Wandhaken / Rosette", home: "Wohnen", samples: "Muster" }
  },
  uk: {
    nav: { home: "Головна", catalog: "Каталог", story: "Про бренд", trade: "Реєстрація", search: "Пошук", samples: "Кошик" },
    hero: { eyebrow: "ФУРНІТУРА ДЛЯ ШТОР · ДЕКОРАТИВНІ ДЕТАЛІ", title: "Ця деталь змінює все.", body: "Китиці, настінні гачки, розетки, бахрома, канти, тасьма й шнури, що завершують оформлення штор і поєднують інтер’єр в одне ціле.", primary: "Переглянути каталог", secondary: "Підібрати зразки" },
    home: { categories: "Фурнітура для штор", latest: "Нові деталі для інтер’єру", latestBody: "Нові моделі, фактури й кольорові поєднання для штор, текстилю та оббивки.", process: "Від ідеї до готового оформлення", processBody: "Допомагаємо підібрати фурнітуру за стилем, кольором, розміром і завданням проєкту.", step1: "Оберіть виріб", step1Body: "Знайдіть потрібну китицю, бахрому, тасьму, шнур, настінний гачок або розетку за артикулом і категорією.", step2: "Порівняйте кольори", step2Body: "Відкрийте варіанти, роздивіться фактуру й додайте відповідні зразки до кошика.", step3: "Узгодьте замовлення", step3Body: "Ми підтвердимо наявність, розміри, склад, ціну й термін постачання.", viewAll: "Відкрити весь каталог", tradeTitle: "Фурнітура, що завершує інтер’єр.", tradeBody: "Підберемо вироби для приватного інтер’єру, дизайн-проєкту, салону штор або регулярних постачань.", talk: "Обговорити проєкт" },
    catalog: { eyebrow: "КАТАЛОГ ФУРНІТУРИ", title: "Деталі для бездоганних штор.", body: "Китиці, настінні гачки, розетки, бахрома, канти, тасьма й шнури в різних стилях і кольорах. Обирайте за артикулом, категорією та фактурою.", search: "Пошук за артикулом або назвою", all: "Усі", results: "артикулів", sort: "Сортування", newest: "Нові", sku: "Артикул А–Я", loadMore: "Показати більше артикулів" },
    product: { new: "Новинка", colours: "варіантів кольору", add: "Додати до кошика", added: "Додано", original: "Оригінальна назва колекції", priceFrom: "від", priceOnRequest: "Ціна за запитом", tradePrice: "Оптова ціна — увійти", availability: "Наявність", inStock: "Є в наявності", lowStock: "Мало в наявності", preorder: "Передзамовлення", availabilityOnRequest: "Уточнити наявність", meter: "м", each: "шт." },
    samples: { name: "Ваше ім’я", email: "Email", phone: "Телефон", company: "Компанія", country: "Країна", city: "Місто", address: "Адреса доставки", postcode: "Поштовий індекс", notes: "Коментар до проєкту", checkout: "Дані замовлення", subtotal: "Сума товарів із підтвердженою ціною", includesOnRequest: "Плюс товари з ціною за запитом", quoteNote: "Сума використовує перевірені оптові ціни Nora TrimTex. Наявність, доставку й відкриті ціни підтвердимо до оплати.", send: "Оформити замовлення", sending: "Оформлення…", success: "Замовлення прийнято", successBody: "Замовлення збережено. Ми підтвердимо вартість, наявність і доставку.", continue: "Продовжити покупки", empty: "Ваш кошик порожній.", error: "Не вдалося оформити замовлення. Спробуйте ще раз." },
    footer: { note: "Фурнітура для штор і декоративні текстильні деталі для інтер’єру.", legal: "© 2026 Nora TrimTex. Усі права захищені." },
    categories: { "tassels-large": "Великі китиці", "tassels-small": "Малі китиці", "tassel-trim": "Бахрома з китицями", "decorative-tapes": "Бордюри й тасьма", fringe: "Бахрома", "cord-fringe": "Шнурова бахрома", cords: "Шнури й канти", holdbacks: "Настінний гачок / розетка", home: "Дім", samples: "Зразок" }
  },
  ru: {
    nav: { home: "Главная", catalog: "Каталог", story: "О бренде", trade: "Регистрация", search: "Поиск", samples: "Корзина" },
    hero: { eyebrow: "ФУРНИТУРА ДЛЯ ШТОР · ДЕКОРАТИВНЫЕ ДЕТАЛИ", title: "Эта деталь меняет всё.", body: "Кисти, настенные крючки, розетки, бахрома, бордюры, тесьмы и шнуры, которые завершают оформление штор и собирают интерьер в единое целое.", primary: "Смотреть каталог", secondary: "Подобрать образцы" },
    home: { categories: "Фурнитура для штор", latest: "Новые детали для интерьера", latestBody: "Свежие модели, фактуры и цветовые сочетания для штор, текстиля и обивки.", process: "От идеи до готового оформления", processBody: "Помогаем подобрать фурнитуру по стилю, цвету, размеру и задаче проекта.", step1: "Выберите изделие", step1Body: "Найдите нужную кисть, бахрому, тесьму, шнур, настенный крючок или розетку по артикулу и категории.", step2: "Сравните цвета", step2Body: "Откройте варианты, изучите фактуру и добавьте подходящие образцы в корзину.", step3: "Согласуйте заказ", step3Body: "Мы подтвердим наличие, размеры, состав, цену и срок поставки.", viewAll: "Открыть весь каталог", tradeTitle: "Фурнитура, которая завершает интерьер.", tradeBody: "Подберём изделия для частного интерьера, дизайн-проекта, салона штор или регулярных поставок.", talk: "Обсудить проект" },
    catalog: { eyebrow: "КАТАЛОГ ФУРНИТУРЫ", title: "Детали для безупречных штор.", body: "Кисти, настенные крючки, розетки, бахрома, бордюры, тесьмы и шнуры в разных стилях и цветах. Выбирайте по артикулу, категории и фактуре.", search: "Поиск по артикулу или названию", all: "Все", results: "артикулов", sort: "Сортировка", newest: "Сначала новые", sku: "Артикул А–Я", loadMore: "Показать больше артикулов" },
    product: { new: "Новинка", colours: "вариантов цвета", add: "Добавить в корзину", added: "Добавлено", original: "Оригинальное название коллекции", priceFrom: "от", priceOnRequest: "Цена по запросу", tradePrice: "Оптовая цена — войти", availability: "Наличие", inStock: "В наличии", lowStock: "Мало в наличии", preorder: "Предзаказ", availabilityOnRequest: "Уточнить наличие", meter: "м", each: "шт." },
    samples: { name: "Ваше имя", email: "Email", phone: "Телефон", company: "Компания", country: "Страна", city: "Город", address: "Адрес доставки", postcode: "Индекс", notes: "Комментарий к проекту", checkout: "Данные заказа", subtotal: "Сумма товаров с подтверждённой ценой", includesOnRequest: "Плюс товары с ценой по запросу", quoteNote: "Сумма рассчитана по проверенным оптовым ценам Nora TrimTex. Наличие, доставку и открытые цены подтвердим до оплаты.", send: "Оформить заказ", sending: "Оформляем…", success: "Заказ принят", successBody: "Заказ сохранён. Мы подтвердим стоимость, наличие и доставку.", continue: "Продолжить покупки", empty: "Ваша корзина пуста.", error: "Не удалось оформить заказ. Попробуйте ещё раз." },
    footer: { note: "Фурнитура для штор и декоративные текстильные детали для интерьера.", legal: "© 2026 Nora TrimTex. Все права защищены." },
    categories: { "tassels-large": "Большие кисти", "tassels-small": "Малые кисти", "tassel-trim": "Бахрома с кистями", "decorative-tapes": "Бордюры, тесьмы", fringe: "Бахрома", "cord-fringe": "Шнуровая бахрома", cords: "Шнуры и канты", holdbacks: "Настенный крючок / розетка", home: "Дом", samples: "Образец" }
  }
} as const;

export const getDictionary = (locale: Locale) => dictionaries[locale];

export const formatColourways = (locale: Locale, count: number) => {
  if (locale === "ru") {
    const lastTwo = count % 100;
    const last = count % 10;
    return `${count} ${lastTwo >= 11 && lastTwo <= 14 ? "вариантов цвета" : last === 1 ? "вариант цвета" : last >= 2 && last <= 4 ? "варианта цвета" : "вариантов цвета"}`;
  }
  if (locale === "uk") {
    const lastTwo = count % 100;
    const last = count % 10;
    return `${count} ${lastTwo >= 11 && lastTwo <= 14 ? "варіантів кольору" : last === 1 ? "варіант кольору" : last >= 2 && last <= 4 ? "варіанти кольору" : "варіантів кольору"}`;
  }
  return `${count} ${dictionaries[locale].product.colours}`;
};
