"use client";
import { useCallback, useEffect, useState } from "react";
import { Check, LoaderCircle, RefreshCw, Search, ShieldCheck, UserX } from "lucide-react";

type AdminUser = { id: string; email: string; role: string; status: string; firstName: string; lastName: string; company?: string; country?: string; city?: string; createdAt: string; cartItems: number; orders: number };
type Detail = { user: AdminUser & { phone?: string; lastLoginAt?: string }; cart: { items: Array<{ sku: string; name: string; quantity: number }>; updatedAt?: string } | null; orders: Array<{ orderNumber: string; status: string; createdAt: string }> };

export function AdminDashboard() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [selected, setSelected] = useState<Detail | null>(null); const [busy, setBusy] = useState(true); const [query, setQuery] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState(""); const [needsLogin, setNeedsLogin] = useState(false);
  const load = useCallback(async () => { setBusy(true); const params = new URLSearchParams({ ...(query ? { search: query } : {}), ...(role ? { role } : {}), ...(status ? { status } : {}) }); const response = await fetch(`/api/admin/users?${params}`); if (response.status === 401 || response.status === 403) setNeedsLogin(true); else if (response.ok) setUsers((await response.json()).data.items); setBusy(false); }, [query, role, status]);
  useEffect(() => { const timer = setTimeout(() => void load(), 200); return () => clearTimeout(timer); }, [load]);
  async function open(id: string) { const response = await fetch(`/api/admin/users/${id}`); if (response.ok) setSelected((await response.json()).data); }
  async function change(id: string, nextStatus: string) { await fetch(`/api/admin/users/${id}/status`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: nextStatus }) }); await load(); if (selected?.user.id === id) await open(id); }
  if (needsLogin) return <AdminLogin />;
  return <div className="admin-shell"><header><div><span>NORA TRIMTEX</span><h1>Клиенты и партнёры</h1></div><button className="button outline" onClick={() => void load()}><RefreshCw size={16} />Обновить</button></header><div className="admin-filters"><label><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Имя, email, компания" /></label><select value={role} onChange={(e) => setRole(e.target.value)}><option value="">Все типы</option><option value="retail">Розница</option><option value="partner">Партнёры</option><option value="admin">Администраторы</option></select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Все статусы</option><option value="pending_approval">Ожидают решения</option><option value="active">Активные</option><option value="email_pending">Не подтвердили email</option><option value="rejected">Отклонённые</option></select></div><div className="admin-layout"><div className="admin-list">{busy && <LoaderCircle className="spin" />}{users.map((user) => <button key={user.id} className={selected?.user.id === user.id ? "active" : ""} onClick={() => void open(user.id)}><span><strong>{user.firstName} {user.lastName}</strong><small>{user.email}</small></span><span><b>{user.role}</b><em data-status={user.status}>{user.status}</em></span><span><small>Корзина: {user.cartItems}</small><small>Заказы: {user.orders}</small></span></button>)}</div><aside className="admin-detail">{selected ? <><span>{selected.user.role}</span><h2>{selected.user.firstName} {selected.user.lastName}</h2><p>{selected.user.email}<br />{selected.user.phone}<br />{selected.user.company}<br />{[selected.user.city, selected.user.country].filter(Boolean).join(", ")}</p>{selected.user.role === "partner" && <div className="admin-actions"><button className="button primary" onClick={() => void change(selected.user.id, "active")}><Check size={16} />Одобрить</button><button className="button outline" onClick={() => void change(selected.user.id, "rejected")}><UserX size={16} />Отклонить</button></div>}<h3>Корзина</h3>{selected.cart?.items?.length ? selected.cart.items.map((item, index) => <div className="admin-cart-line" key={`${item.sku}-${index}`}><span>{item.sku}<small>{item.name}</small></span><b>× {item.quantity}</b></div>) : <p>Корзина пуста</p>}<h3>Заказы</h3>{selected.orders.length ? selected.orders.map((order) => <p key={order.orderNumber}>{order.orderNumber} · {order.status}</p>) : <p>Заказов нет</p>}</> : <div className="admin-empty"><ShieldCheck /><p>Выберите клиента</p></div>}</aside></div></div>;
}

function AdminLogin() { const [error, setError] = useState(""); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const body = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/account/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (response.ok) location.reload(); else setError("Неверные данные или нет доступа администратора."); } return <form className="admin-login" onSubmit={submit}><span>NORA TRIMTEX ADMIN</span><h1>Вход в управление</h1><label>Email<input name="email" type="email" required /></label><label>Пароль<input name="password" type="password" required /></label>{error && <p>{error}</p>}<button className="button primary">Войти</button></form>; }
